from django.conf.urls.defaults import *

urlpatterns = patterns('butkus.team.views',
    (r'^$', 'index'),
    (r'^(?P<team_id>\d+)/$', 'index'),
    (r'^index/$', 'index'),
    (r'^(?P<team_id>\d+)/index/$', 'index'),
    (r'^(?P<team_id>\d+)/boxscores/$', 'boxscores'),
    (r'^(?P<team_id>\d+)/boxscores/season/(?P<season>\d+)/$', 'boxscores'),
    (r'^(?P<team_id>\d+)/boxscores/season/(?P<season>\d+)/week/(?P<week>\d+)/$', 'boxscores'),
    (r'^(?P<team_id>\d+)/change_current_team/$', 'change_current_team'),
    (r'^(?P<team_id>\d+)/draft/$', 'draft'),
    (r'^(?P<team_id>\d+)/draft/season/(?P<season>\d+)/$', 'draft'),
    (r'^(?P<team_id>\d+)/draft/season/(?P<season>\d+)/sort/(?P<sort>[a-zA-Z]+)/$', 'draft'),
    (r'^(?P<team_id>\d+)/pickups/$', 'pickups'),
    (r'^(?P<team_id>\d+)/pickups/season/(?P<season>\d+)/$', 'pickups'),
    (r'^(?P<team_id>\d+)/roster/$', 'roster'),
    (r'^(?P<team_id>\d+)/roster/season/(?P<season>\d+)/$', 'roster'),
    (r'^(?P<team_id>\d+)/roster/season/(?P<season>\d+)/week/(?P<week>\d+)/$', 'roster'),
    (r'^(?P<team_id>\d+)/roster/(?P<roster_id>\d+)/move/season/(?P<season>\d+)/week/(?P<week>\d+)/$', 'roster_move'),
    (r'^(?P<team_id>\d+)/roster/(?P<roster_id>\d+)/cut/season/(?P<season>\d+)/week/(?P<week>\d+)/$', 'roster_cut'),
    (r'^(?P<team_id>\d+)/starters/$', 'starters'),
    (r'^(?P<team_id>\d+)/starters/season/(?P<season>\d+)/$', 'starters'),
    (r'^(?P<team_id>\d+)/starters/season/(?P<season>\d+)/week/(?P<week>\d+)/$', 'starters'),
    (r'^(?P<team_id>\d+)/starters/season/(?P<season>\d+)/week/(?P<week>\d+)/edit/$', 'starters_edit'),
    (r'^(?P<team_id>\d+)/trades/$', 'trades'),
)
