from django.conf.urls.defaults import *

urlpatterns = patterns('butkus.league.views',
    (r'^$', 'index'),
    (r'^index/$', 'index'),
    (r'^draft/$', 'draft'),
    (r'^draft/season/(?P<season>\d+)/$', 'draft'),
    (r'^draft/season/(?P<season>\d+)/sort/(?P<sort>[a-zA-Z]+)/$', 'draft'),
    (r'^owners/$', 'owners'),
    (r'^pickups/$', 'pickups'),
    (r'^pickups/season/(?P<season>\d+)/$', 'pickups'),
    (r'^rosters/$', 'rosters'),
    (r'^rosters/season/(?P<season>\d+)/$', 'rosters'),
    (r'^rosters/season/(?P<season>\d+)/week/(?P<week>\d+)/$', 'rosters'),
    (r'^schedule/$', 'schedule'),
    (r'^schedule/season/(?P<season>\d+)/$', 'schedule'),
    (r'^standings/$', 'standings'),
    (r'^standings/season/(?P<season>\d+)/$', 'standings'),
    (r'^standings/season/(?P<season>\d+)/edit/$', 'standings_edit'),
    (r'^standings/season/(?P<season>\d+)/sort/(?P<sort>[a-zA-Z0-9]+)/$', 'standings'),
    (r'^starters/$', 'starters'),
    (r'^starters/season/(?P<season>\d+)/$', 'starters'),
    (r'^starters/season/(?P<season>\d+)/week/(?P<week>\d+)/$', 'starters'),
    (r'^trophy/$', 'trophy'),
)
